name: Deploy Terraform Module
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
      directory:
        required: true
        type: string
      backend_bucket:
        required: true
        type: string
      backend_key:
        required: true
        type: string
      tf_action:
        required: true
        type: string
        default: 'apply -auto-approve'
      artifact_name:
        required: true
        type: string
jobs:
  execute_terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{inputs.directory}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact_name}}
          path: ~/
        continue-on-error: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{inputs.backend_bucket}}" -backend-config="workspace_key_prefix=environments" -backend-config="key=${{inputs.backend_key}}" -backend-config="region=us-east-1"

      - name: Terraform Workspace Creation
        run: terraform workspace new ${{inputs.environment}}
        continue-on-error: true

      - name: Terraform Workspace Selection
        run: terraform workspace select ${{inputs.environment}}
        continue-on-error: true

      - name: Terraform Action (${{inputs.tf_action}})
        run: terraform ${{inputs.tf_action}}
        env:
          TF_VAR_lambda_zip_path: "~/index.zip"

